const header=document.querySelector('.topbar');let last=0;window.addEventListener('scroll',()=>{const y=window.scrollY;if(y>last&&y>120)header.style.transform='translateY(-100%)';else header.style.transform='translateY(0)';last=y;});
const lightbox=document.querySelector('.lightbox');const lightboxImage=document.querySelector('.lightbox-image');const closeLightbox=()=>{lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');lightboxImage.src='';};document.querySelectorAll('.photo-button').forEach(button=>{button.addEventListener('click',()=>{lightboxImage.src=button.dataset.full;lightboxImage.alt=button.querySelector('img').alt;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');});});document.querySelector('.lightbox-close').addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox();});
const teleportLinks={KRUSH:'https://maps.secondlife.com/secondlife/Love%20is%20Love/74/9/2086',SOHO:'https://maps.secondlife.com/secondlife/Soho%20Island/60/192/3024'};
document.querySelectorAll('.agenda-list .event').forEach(event=>{const title=(event.querySelector('b')?.textContent||'').toUpperCase();const club=title.includes('KRUSH')?'KRUSH':title.includes('SOHO')?'SOHO':null;if(club&&teleportLinks[club]){const wrap=document.createElement('div');wrap.className='event-actions';const a=document.createElement('a');a.href=teleportLinks[club];a.className='teleport-button';a.textContent='↗ TELEPORT TO '+club;a.target='_blank';a.rel='noopener';wrap.appendChild(a);event.appendChild(wrap);}});
const teleportStyle=document.createElement('style');teleportStyle.textContent='.agenda-list .event{position:relative}.event-actions{display:flex;align-items:center;justify-content:flex-end;margin-left:auto;padding-left:16px}.teleport-button{display:inline-flex;align-items:center;justify-content:center;border:1px solid #4b4b52;color:#fff;background:transparent;padding:10px 13px;font:900 8px Inter,Arial,sans-serif;letter-spacing:.12em;text-decoration:none;white-space:nowrap;transition:.2s}.teleport-button:hover{background:#e31b23;border-color:#e31b23;transform:translateY(-1px)}@media(max-width:760px){.event-actions{grid-column:1/-1;margin-left:0;padding-left:0;margin-top:8px;justify-content:flex-start}.teleport-button{width:100%}}';document.head.appendChild(teleportStyle);
const discordButton=document.querySelector('#booking a[href*="discord.com"]');if(discordButton){discordButton.addEventListener('click',e=>{e.preventDefault();window.location.href='discord://-/users/110883002162163712';setTimeout(()=>{window.open('https://discord.com/users/110883002162163712','_blank','noopener');},1200);});}
const pressSection=document.querySelector('#press');if(pressSection){const pressButton=pressSection.querySelector('.press-head .button');if(pressButton){const download=document.createElement('a');download.className='button';download.href='DJ_ZRO_EPK_Press_Kit_v2.pdf';download.setAttribute('download','DJ_ZRO_EPK_Press_Kit_v2.pdf');download.textContent='DOWNLOAD PRESS KIT';pressButton.replaceWith(download);}}
const visitorStyle=document.createElement('style');visitorStyle.textContent='.visitor-counter{display:flex;justify-content:center;align-items:center;gap:8px;margin:18px auto 0;font:700 9px Inter,Arial,sans-serif;letter-spacing:.16em;text-transform:uppercase;color:#777}.visitor-counter strong{color:#fff;font:800 10px Inter,Arial,sans-serif;letter-spacing:.12em}.visitor-counter span{color:#777}.visitor-counter a{color:#fff;text-decoration:none}';document.head.appendChild(visitorStyle);const visitorCounter=document.createElement('div');visitorCounter.className='visitor-counter';visitorCounter.innerHTML='<span>VISITORS</span><strong id="visitor-count">...</strong>';document.body.appendChild(visitorCounter);window.zroVisitorCount=function(response){const el=document.getElementById('visitor-count');if(el&&response&&typeof response.value!=='undefined')el.textContent=response.value.toLocaleString();};const counterScript=document.createElement('script');counterScript.src='https://counterapi.com/api/djzro.github.io/view/unique-visitors?unique=true&callback=zroVisitorCount';counterScript.async=true;document.body.appendChild(counterScript);
const mixStyle=document.createElement('link');mixStyle.rel='stylesheet';mixStyle.href='mixes.css?v=2';document.head.appendChild(mixStyle);
